-
  name: 'gw2challenges'
  uriPattern: '<gw2challengesSubroutes>'
  subRoutes:
    PassePartoutSubroutes:
      package: schilter.gw2challenges

-
  name: 'Index'
  uriPattern: ''
  defaults:
    '@package':    'schilter.gw2challenge'
    '@controller': 'Mini'
    '@action':     'index'
    '@format':     'html'